[project]
name = "glslt"

[project.scripts]
glsltc = "glslt:main"

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[tools.maturin]
bindings = "pyo3"
cargo-extra-args = "--features python"
strip = true
